name: render-app-deployment

on:
  release:
    types:
      - created
    branches:
      - main

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Check if release target is main
        run: |
          if [ "${{ github.event.release.target_commitish }}" != "main" ]; then
            echo "Not on the main branch. Skipping the curl command."
            exit 0
          fi

      - name: Curl Render to run new deploy
        if: success()
        run: |
          CURL_URL="https://api.render.com/deploy/${{secrets.RENDER_DEPLOY_APP_TOKEN}}?key=${{secrets.RENDER_DEPLOY_KEY}}&ref=${{ github.event.release.target_commitish }}"

          HTTP_STATUS=$(curl -i -X POST "${CURL_URL}" -o /dev/null -w "%{http_code}")
          
          if [[ $HTTP_STATUS -ge 200 && $HTTP_STATUS -lt 
